menor_unidade = 32
# altura: 20 unidades * 32 -> 640px
# largura: 35 unidades * 32 -> 1120px


matrix_terreno1 = [
    '                                   ',
    '                           I       ',
    '                                   ',
    '                                   ',
    '                                   ',
    '                                   ',
    '              BBBB                 ',
    '              BBBB                 ',
    '              BBBB                 ',
    '              BBBB                 ',
    '                                   ',
    '                                   ',
    'PPPPPPPPPPPPPPP                    ',
    '                                   ',
    '                                   ',
    '                                   ',
    '                                   ',
    '                                   ',
    '                                   ',
    '                         PPPPPPPPPP',
    '                J                  ',
    '                         P         ',
]

matrix_terreno2 = [
    '                                   ',
    '                                   ',
    '                                   ',
    '                                   ',
    '                                   ',
    '                                   ',
    '              BBBB                 ',
    '              BBBB                 ',
    '              BBBB                 ',
    '              BBBB                 ',
    '                                   ',
    '                                   ',
    '                                   ',
    '                                   ',
    '                                   ',
    '                                   ',
    '                                   ',
    '                                   ',
    '                                   ',
    '                         PPPPPPPPPP',
    '                         P         ',
    '                         P         ',
]

matrix_terreno3 = [
    '                                   ',
    '                                   ',
    '                                   ',
    '                                   ',
    '                                   ',
    '                                   ',
    '              BBBB                 ',
    '              BBBB                 ',
    '              BBBB                 ',
    '              BBBB                 ',
    '                                   ',
    '                                   ',
    '                                   ',
    '                                   ',
    '                                   ',
    '                                   ',
    '                                   ',
    '                                   ',
    '                                   ',
    '                         PPPPPPPPPP',
    '                         P         ',
    '                         P         ',
]
