# altura: 20 unidades * 32 -> 640px
# largura: 35 unidades * 32 -> 1120px


matriz_terreno1 = [
    '                                   ',
    '                                   ',
    '                                   ',
    '         LIMITE DE CIMA            ',
    'PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP',
    'P                                 P',
    'P                                 P',
    'P       PP              PP        P',
    'P       PP      PP      PP        P',
    'P               PP                P',
    'P               PP                P',
    'P               PP                P',
    'P               PP                P',
    'P  PP                         PP  P',
    'P  PP           J             PP  P',
    'P                                 P',
    'P               PP                P',
    'P               PP                P',
    'P               PP                P',
    'P       PP      PP      PP        P',
    'P       PP      PP      PP        P',
    'P                                 P',
    'P                                 P',
    'PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP',
]

matriz_terreno2 = [
    '                                   ',
    '                                   ',
    '                                   ',
    '         LIMITE DE CIMA            ',
    'PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP',
    'P                                 P',
    'P  PP                         PP  P',
    'P       PP              PP        P',
    'P       PP      PP      PP        P',
    'P                                 P',
    'P                                 P',
    'P               PP                P',
    'P               PP                P',
    'P  PP       P        P        PP  P',
    'P  PP       P   J    P        PP  P',
    'P           P        P            P',
    'P               PP                P',
    'P               PP                P',
    'P                                 P',
    'P       PP              PP        P',
    'P       PP      PP      PP        P',
    'P  PP                         PP  P',
    'P                                 P',
    'PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP',
]

matriz_terreno3 = [
    '                                   ',
    '                                   ',
    '                                   ',
    '         LIMITE DE CIMA            ',
    'PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP',
    'P                                 P',
    'P                                 P',
    'P       PP  PP  PP  PP  PP        P',
    'P  PP   PP  PP  PP  PP  PP    PP  P',
    'P  PP                         PP  P',
    'P                                 P',
    'P                                 P',
    'P                                 P',
    'P  PP       PP      PP        PP  P',
    'P  PP       PP  J   PP        PP  P',
    'P                                 P',
    'P                                 P',
    'P                                 P',
    'P  PP                         PP  P',
    'P  PP   PP  PP  PP  PP  PP    PP  P',
    'P       PP  PP  PP  PP  PP        P',
    'P                                 P',
    'P                                 P',
    'PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP',
]
